/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface MediaAttachment {
  'blob' : ExternalBlob,
  'attachmentType' : MediaAttachmentType,
}
export type MediaAttachmentType = { 'video' : null } |
  { 'photo' : null };
export interface Message {
  'text' : string,
  'sender' : Principal,
  'timestamp' : bigint,
  'attachments' : Array<MediaAttachment>,
}
export interface UserProfile {
  'fullName' : string,
  'phoneNumber' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changePassword' : ActorMethod<[string, string], undefined>,
  'checkPassword' : ActorMethod<[string], boolean>,
  'checkPhoneNumberAvailability' : ActorMethod<[string], boolean>,
  'createConversation' : ActorMethod<[Array<Principal>], string>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getAllVerifiedPhoneNumbers' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatchingContacts' : ActorMethod<[Array<string>], Array<UserProfile>>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getProfilePicture' : ActorMethod<[Principal], [] | [ExternalBlob]>,
  'getUserConversations' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasPassword' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'removePassword' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, Message], undefined>,
  'setPassword' : ActorMethod<[string], undefined>,
  'uploadProfilePicture' : ActorMethod<[ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];